### PR TITLE
Use Promise to wait for response if it is not ready

### LINKED ISSUE #10: Properly handling 'just unfrozed' requests
In some cases `gh-latest-repos` returns just an empty request `[]`. 

**My hypothesis of cause**

I observe in `now` that a [*frozen* microservice](https://zeit.co/docs/guides/app-lifecycle-and-scalability) means the process just been killed and only be activated again if a request are made, which is a problem because variables are lost and request to GitHub  API have to be reinitiated again.

Because variables are lost, there's race condition between client request and request to GitHub API, hence `gh-latest-repos` just returns `[]` instead of waiting for response from GitHub API.

And because of #9 I realized that I can't make a workaround by requesting to `gh-latest-repos` twice. :cry:

**Solution**

I have [my own patch](https://github.com/willnode/gh-latest-repos/commit/cf3feb5da9fe473c9bce1c3c25023bf0a3babda2) to send [202 (Accepted)](https://stackoverflow.com/a/15655812/3908409) without cache control in case empty `[]` will send (so the client can make another request again)

```js
if (responseText === '[]') {
	response.statusCode = 202;
	response.end('[]');
	return;
}
```

*I can made a PR for this but I realize this is too much for just solving this problem so I have a better idea:*

Make `fetchRepos()` to be synchronous?

### PR DESCRIPTION
**Pull request by willnode**
Using Promise just like what I promise to fix #10.

Jokes aside, I've been checking this method for couple of times, and it worked great. I don't know how to write tests for this scenario, unfortunately.

Thanks for the tip on `Promise`, by the way! I learned something new along the way.

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is not really what I had in mind. I meant just assigning a Promise to `responseText` that fetches the repos, and then always `await` it in `module.exports = (request, response)`. A promise is only resolved once, so it will only wait for it to resolve to first time. The next times it's cached.

**Comment by willnode** [comment]
Oh, I thought it would be a disanvantage as `fetchRepos` would need to be triggered by  first request instead right after `npm start`. But well I hope this one is right.

**Comment by willnode** [comment]
Hmm. 500 error on test. I swear it works when I `npm start`.

**Comment by sindresorhus** [comment]
Closing for lack of activity.

**Pull request closed without merging**
