### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by kevva**
Had to add a trailing slash to the URL for `nock` to work. Shouldn't affect anything AFAIK.

### CODE REVIEW

**Comment by kevva** [comment]
Weird that tests failing, works fine locally. I suspect this is due to a race condition here https://github.com/sindresorhus/gh-latest-repos/blob/master/index.js#L64. The test might finish earlier than `fetchRepos`.

**Comment by sindresorhus** [comment]
Yup, I think that's it too. You could maybe use `require('delay')`.

**Comment by kevva** [comment]
> Yup, I think that's it too. You could maybe use require('delay').

That works, but seems like using `/` at the end of the URL doesn't (`404`). `nock` had a workaround for adding a trailing slash to the path though so should be fine now.

**Comment by sindresorhus** [comment]
Awesome to have some tests for this. Thanks! I should have done it initially. Was just too lazy 😛

**Comment by kevva** [comment]
Hah, luckily I had written tests for some `micro` stuff before :).

**Pull request merged**
